'use client';

import { useMemo, useState, type ReactNode } from 'react';
import { repository } from '@/lib/repository';
import { dqSubjectName as dailyQuestionSubjectName, dqSubjects as seededDQSubjects } from '@/lib/daily-questions';
import { masteryLabel, matchesMastery, type MasteryFilter } from '@/lib/mastery';
import type { Card, CardType, Chapter, DailyQuestion, DQType, Relation, ReviewState, Subject } from '@/lib/types';

const legacyToSubject: Record<string,string> = {
  'dq-xingfa':'criminal-law', 'dq-xingsu':'criminal-procedure', 'dq-xingzheng':'administrative-law',
  'dq-minshang':'civil-commercial-law', 'dq-sanguo':'three-international-laws', 'dq-shangjingzhi':'commercial-economic-ip',
  'dq-minsu':'civil-procedure',
};
const subjectToLegacy: Record<string,string> = Object.fromEntries(Object.entries(legacyToSubject).map(([legacy, subject]) => [subject, legacy]));
const typeName: Record<CardType,string> = { mnemonic:'口诀默写', judgment:'判断题', recall:'背诵卡' };
const relationName: Record<Relation['kind'],string> = { confusable:'易混', exception:'例外', counterexample:'反例', statute:'法条', trap:'陷阱' };
const titleOf = (card: Card) => card.prompt.replace(/^请完整默写：\s*/, '');

interface Props {
  cards: Card[];
  questions: DailyQuestion[];
  subjects: Subject[];
  chapters: Chapter[];
  states: ReviewState[];
  relations: Relation[];
  constitutionView?: (selected: string, onSelect: (id: string) => void) => ReactNode;
  onChanged(): Promise<void>;
  onOpen(card: Card): void;
  onQuick(card: Card): void;
  onExam(card: Card): void;
}

type CardDraft = Card & { resetProgress?: boolean; segmentText?: string };
type QuestionDraft = DailyQuestion & { resetProgress?: boolean; optionText?: string };

const now = () => new Date().toISOString();
const blankCard = (subjects: Subject[], chapters: Chapter[]): CardDraft => {
  const subjectId = subjects[0]?.id ?? 'theory';
  return { id: crypto.randomUUID(), subjectId, chapterId: chapters.find(c => c.subjectId === subjectId)?.id ?? '', type:'mnemonic', prompt:'', answer:'', explanation:'', tags:[], source:'个人整理', createdAt:now(), updatedAt:now(), resetProgress:true, segmentText:'' };
};
const blankQuestion = (questions: DailyQuestion[]): QuestionDraft => {
  const subjectId = questions[0]?.subjectId ?? seededDQSubjects[0]?.id ?? 'dq-xingfa';
  const maxNumber = Math.max(0, ...questions.filter(q => q.subjectId === subjectId).map(q => q.number));
  return { id:crypto.randomUUID(), subjectId, number:maxNumber+1, source:'个人整理', qtype:'single', stem:'', options:[{key:'A',text:''},{key:'B',text:''}], answer:'A', analysis:'', tags:[], createdAt:now(), updatedAt:now(), resetProgress:true, optionText:'A. \nB. ' };
};

export default function ContentLibrary(props: Props) {
  const { cards, questions, subjects, chapters, states, relations } = props;
  const [tab,setTab]=useState<'cards'|'daily'>('cards');
  const [subjectId,setSubjectId]=useState('all');
  const [chapterId,setChapterId]=useState('all');
  const [query,setQuery]=useState('');
  const [typeFilter,setTypeFilter]=useState('all');
  const [masteryFilter,setMasteryFilter]=useState<MasteryFilter>('all');
  const [selectedCardId,setSelectedCardId]=useState<string|null>(null);
  const [selectedQuestionId,setSelectedQuestionId]=useState<string|null>(null);
  const [cardDraft,setCardDraft]=useState<CardDraft|null>(null);
  const [questionDraft,setQuestionDraft]=useState<QuestionDraft|null>(null);
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const [showArchived,setShowArchived]=useState(false);

  const stateMap=useMemo(()=>new Map(states.map(state=>[state.cardId,state])),[states]);
  const canonicalSubject = (id:string) => legacyToSubject[id] ?? id;
  const activeCards=cards.filter(card=>showArchived?Boolean(card.archivedAt):!card.archivedAt);
  const activeQuestions=questions.filter(question=>showArchived?Boolean(question.archivedAt):!question.archivedAt);
  const visibleChapters=chapters.filter(chapter=>subjectId==='all'||chapter.subjectId===canonicalSubject(subjectId)).sort((a,b)=>a.order-b.order);
  const cardBase=activeCards.filter(card=>(subjectId==='all'||card.subjectId===subjectId)&&(chapterId==='all'||card.chapterId===chapterId)&&(typeFilter==='all'||card.type===typeFilter)&&`${card.prompt}${card.answer}${card.tags.join('')}${card.explanation}`.toLowerCase().includes(query.toLowerCase()));
  const visibleCards=cardBase.filter(card=>matchesMastery(stateMap.get(card.id),masteryFilter));
  const visibleQuestions=activeQuestions.filter(question=>(subjectId==='all'||question.subjectId===subjectId)&&(chapterId==='all'||question.chapterId===chapterId)&&`${question.stem}${question.analysis??''}${question.tags?.join('')??''}`.toLowerCase().includes(query.toLowerCase()));
  const selectedCard=activeCards.find(card=>card.id===selectedCardId);
  const selectedQuestion=activeQuestions.find(question=>question.id===selectedQuestionId);
  const selectedRelations=selectedCard?relations.filter(r=>r.fromCardId===selectedCard.id||r.toCardId===selectedCard.id):[];
  const dqSubjectOptions=useMemo(()=>{
    const options=new Map(seededDQSubjects.map(subject=>[subject.id,subject.name]));
    for(const subject of subjects){
      const id=subjectToLegacy[subject.id]??subject.id;
      if(!options.has(id)) options.set(id,subject.name);
    }
    return [...options.entries()].map(([id,name])=>({id,name}));
  },[subjects]);
  const dqSubjectOrder=new Map(dqSubjectOptions.map((subject,index)=>[subject.id,index]));
  const qSubjectIds=[...new Set([...dqSubjectOptions.map(subject=>subject.id),...activeQuestions.map(question=>question.subjectId)])].sort((a,b)=>(dqSubjectOrder.get(a)??Number.MAX_SAFE_INTEGER)-(dqSubjectOrder.get(b)??Number.MAX_SAFE_INTEGER));
  const qSubjectName=(id:string)=>dailyQuestionSubjectName(id)!==id?dailyQuestionSubjectName(id):subjects.find(subject=>subject.id===canonicalSubject(id))?.name??id;
  const masteryOptions: {id:MasteryFilter;label:string}[]=[{id:'all',label:'全部'},{id:'weak',label:'只看不会'},{id:'new',label:'未学习'},{id:'again',label:'忘记'},{id:'hard',label:'模糊'},{id:'good',label:'记住'},{id:'easy',label:'熟练'}];

  const editCard=(card:Card)=>setCardDraft({...card,segmentText:card.mnemonicSegments?.map(s=>`${s.text} => ${s.knowledgePoint}`).join('\n')??'',resetProgress:false});
  const copyCard=(card:Card)=>setCardDraft({...card,id:crypto.randomUUID(),prompt:`${titleOf(card)}（副本）`,createdAt:now(),updatedAt:now(),segmentText:card.mnemonicSegments?.map(s=>`${s.text} => ${s.knowledgePoint}`).join('\n')??'',resetProgress:true});
  const saveCard=async()=>{if(!cardDraft?.prompt.trim()||!cardDraft.answer.trim()||!cardDraft.chapterId){setMessage('请填写标题、答案并选择章节');return}setBusy(true);try{const segments=(cardDraft.segmentText??'').split(/\r?\n/).map(line=>line.split(/\s*=>\s*/)).filter(parts=>parts[0]?.trim()).map(parts=>({text:parts[0].trim(),knowledgePoint:(parts[1]??parts[0]).trim()}));const resetProgress=cardDraft.resetProgress;const card={...cardDraft};delete card.resetProgress;delete card.segmentText;await repository.saveCard({...card,prompt:card.prompt.trim(),answer:card.answer.trim(),mnemonicSegments:segments.length?segments:undefined,tags:card.tags.filter(Boolean),updatedAt:now()},Boolean(resetProgress));await props.onChanged();setCardDraft(null);setSelectedCardId(card.id);setMessage('知识卡已保存并同步到当前账号')}finally{setBusy(false)}};
  const addChapter=async(subject:string)=>{const name=window.prompt('新章节名称');if(!name?.trim())return;const siblings=chapters.filter(ch=>ch.subjectId===subject);const chapter:Chapter={id:`custom-${crypto.randomUUID()}`,subjectId:subject,name:name.trim(),order:Math.max(0,...siblings.map(ch=>ch.order))+1};await repository.saveChapter(chapter);await props.onChanged();setCardDraft(draft=>draft?{...draft,chapterId:chapter.id}:draft)};

  const editQuestion=(question:DailyQuestion)=>setQuestionDraft({...question,optionText:question.options.map(o=>`${o.key}. ${o.text}`).join('\n'),resetProgress:false});
  const copyQuestion=(question:DailyQuestion)=>setQuestionDraft({...question,id:crypto.randomUUID(),number:Math.max(0,...activeQuestions.filter(q=>q.subjectId===question.subjectId).map(q=>q.number))+1,createdAt:now(),updatedAt:now(),optionText:question.options.map(o=>`${o.key}. ${o.text}`).join('\n'),resetProgress:true});
  const saveQuestion=async()=>{if(!questionDraft?.stem.trim()){setMessage('请填写题干');return}const options=(questionDraft.optionText??'').split(/\r?\n/).map((line,index)=>{const match=line.match(/^\s*([A-Z])\s*[.、:：]\s*(.*)$/i);return {key:(match?.[1]??String.fromCharCode(65+index)).toUpperCase(),text:(match?.[2]??line).trim()}}).filter(o=>o.text);if(options.length<2){setMessage('每日一题至少需要两个选项');return}const answer=questionDraft.answer?.toUpperCase().replace(/[^A-Z]/g,'')||null;if(answer&&[...answer].some(key=>!options.some(option=>option.key===key))){setMessage('正确答案包含不存在的选项');return}setBusy(true);try{const resetProgress=questionDraft.resetProgress;const question={...questionDraft};delete question.resetProgress;delete question.optionText;await repository.saveDailyQuestion({...question,stem:question.stem.trim(),options,answer,updatedAt:now()},Boolean(resetProgress));await props.onChanged();setQuestionDraft(null);setSelectedQuestionId(question.id);setMessage('每日一题已保存并同步到当前账号')}finally{setBusy(false)}};

  const archiveCard=async(card:Card)=>{const archived=!card.archivedAt;if(!archived||window.confirm('归档后本卡不会进入复习和组卷，但可在归档箱恢复。确认归档吗？')){await repository.archiveCard(card.id,archived);setSelectedCardId(null);await props.onChanged();setMessage(archived?'知识卡已移入归档箱':'知识卡已恢复')}};
  const archiveQuestion=async(question:DailyQuestion)=>{const archived=!question.archivedAt;if(!archived||window.confirm('归档后本题不会进入每日一题练习，但可在归档箱恢复。确认归档吗？')){await repository.archiveDailyQuestion(question.id,archived);setSelectedQuestionId(null);await props.onChanged();setMessage(archived?'每日一题已移入归档箱':'每日一题已恢复')}};
  const chooseSubject=(id:string)=>{setSubjectId(id);setChapterId('all')};
  return <section className="page-panel content-library">
    <div className="content-library-head"><div><p className="section-kicker">个人内容主库</p><h2>{showArchived?'归档箱':tab==='cards'?'知识卡库':'每日一题库'}</h2><p>新增和修改会直接保存到当前账号；管理员可在用户管理中选择范围分发。</p></div><div className="content-library-actions"><button type="button" onClick={()=>{setShowArchived(!showArchived);setSelectedCardId(null);setSelectedQuestionId(null)}}>{showArchived?'返回活动题库':'查看归档箱'}</button>{!showArchived&&<button className="library-add" type="button" onClick={()=>tab==='cards'?setCardDraft(blankCard(subjects,chapters)):setQuestionDraft(blankQuestion(activeQuestions))}>＋ 新增{tab==='cards'?'知识卡':'每日一题'}</button>}</div></div>
    <div className="content-library-tabs"><button className={tab==='cards'?'active':''} onClick={()=>{setTab('cards');setSubjectId('all');setChapterId('all')}}>知识卡库 <span>{activeCards.length}</span></button><button className={tab==='daily'?'active':''} onClick={()=>{setTab('daily');setSubjectId('all');setChapterId('all')}}>每日一题库 <span>{activeQuestions.length}</span></button></div>
    <div className="toolbar library-toolbar"><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==='cards'?'搜索标题、答案、法条或标签':'搜索题干、解析或标签'}/></div><select value={chapterId} onChange={e=>setChapterId(e.target.value)}><option value="all">全部章节</option>{visibleChapters.map(ch=><option value={ch.id} key={ch.id}>{ch.name}</option>)}</select>{tab==='cards'&&<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">全部类型</option><option value="mnemonic">口诀默写</option><option value="judgment">判断题</option><option value="recall">背诵卡</option></select>}</div>
    <div className="subject-tabs"><button className={subjectId==='all'?'active':''} onClick={()=>chooseSubject('all')}>全部</button>{(tab==='cards'?subjects.map(subject=>({id:subject.id,name:subject.name,count:activeCards.filter(card=>card.subjectId===subject.id).length})):qSubjectIds.map(id=>({id,name:qSubjectName(id),count:activeQuestions.filter(q=>q.subjectId===id).length}))).map(item=><button className={subjectId===item.id?'active':''} onClick={()=>chooseSubject(item.id)} key={item.id}>{item.name} <span>{item.count}</span></button>)}</div>
    {tab==='cards'&&subjectId==='theory'&&props.constitutionView?.(chapterId,setChapterId)}
    {tab==='cards'&&<div className="mastery-filter-bar"><span>熟悉度</span><div>{masteryOptions.map(option=><button type="button" className={masteryFilter===option.id?'active '+option.id:option.id} onClick={()=>setMasteryFilter(option.id)} key={option.id}><strong>{option.label}</strong><small>{cardBase.filter(card=>matchesMastery(stateMap.get(card.id),option.id)).length}</small></button>)}</div><p>显示 <strong>{visibleCards.length}</strong> 张</p></div>}
    <div className="library-table"><div className="table-head"><span>{tab==='cards'?'知识卡':'每日一题'}</span><span>章节 / 来源</span><span>{tab==='cards'?'状态':'题型'}</span><span>操作</span></div>{tab==='cards'?visibleCards.map(card=><div className="table-row" key={card.id}><button type="button" onClick={()=>setSelectedCardId(card.id)}><span className={'type-dot '+card.type}/><strong>{titleOf(card)}</strong><small>{typeName[card.type]} · {card.tags.join(' · ')}</small></button><span>{chapters.find(ch=>ch.id===card.chapterId)?.name??'未归类'}</span><span className={'mastery '+(stateMap.get(card.id)?.lastRating??'new')}>{masteryLabel(stateMap.get(card.id))}</span><button type="button" onClick={()=>editCard(card)}>编辑</button></div>):visibleQuestions.map(question=><div className="table-row" key={question.id}><button type="button" onClick={()=>setSelectedQuestionId(question.id)}><strong>第{question.number}题 · {question.stem}</strong><small>{question.tags?.join(' · ')||'未设置标签'}</small></button><span>{question.source||'未注明'}</span><span>{question.qtype==='multiple'?'多选':question.qtype==='uncertain'?'不定项':'单选'}</span><button type="button" onClick={()=>editQuestion(question)}>编辑</button></div>)}</div>
    {message&&<div className="settings-message" role="status">{message}</div>}
    {selectedCard&&<div className="library-detail-overlay" onClick={()=>setSelectedCardId(null)}><aside className="library-detail-drawer" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><header><div><p className="section-kicker">{typeName[selectedCard.type]}</p><h2>{titleOf(selectedCard)}</h2><p>{subjects.find(s=>s.id===selectedCard.subjectId)?.name} · {chapters.find(c=>c.id===selectedCard.chapterId)?.name}</p></div><button onClick={()=>setSelectedCardId(null)}>×</button></header><div className="library-detail-scroll"><section className="library-detail-answer"><strong>{selectedCard.type==='mnemonic'?'完整口诀':selectedCard.type==='judgment'?'正确结论':'参考答案'}</strong><p>{selectedCard.type==='judgment'?(selectedCard.judgmentAnswer?'正确':'错误'):selectedCard.answer}</p></section>{selectedCard.mnemonicSegments?.length?<section className="library-detail-segments"><strong>口诀逐句对应</strong>{selectedCard.mnemonicSegments.map((segment,index)=><div key={index}><span>{segment.text}</span><i>→</i><p>{segment.knowledgePoint}</p></div>)}</section>:null}{selectedCard.explanation&&<section><strong>详细解释</strong><p>{selectedCard.explanation}</p></section>}{selectedCard.statute&&<section><strong>法条 / 依据</strong><p>{selectedCard.statute}</p></section>}{selectedRelations.length>0&&<section className="library-detail-relations"><strong>关联知识</strong>{selectedRelations.map(relation=>{const id=relation.fromCardId===selectedCard.id?relation.toCardId:relation.fromCardId;const target=activeCards.find(card=>card.id===id);return target?<button key={relation.id} onClick={()=>setSelectedCardId(target.id)}><span>{relationName[relation.kind]}</span><div><b>{titleOf(target)}</b><small>{relation.note}</small></div>→</button>:null})}</section>}</div><footer><button onClick={()=>void archiveCard(selectedCard)}>{selectedCard.archivedAt?'恢复':'归档'}</button>{!selectedCard.archivedAt&&<><button onClick={()=>copyCard(selectedCard)}>复制</button><button onClick={()=>editCard(selectedCard)}>编辑</button><button onClick={()=>props.onQuick(selectedCard)}>速记</button><button onClick={()=>props.onExam(selectedCard)}>组卷</button><button className="primary" onClick={()=>props.onOpen(selectedCard)}>开始学习 →</button></>}</footer></aside></div>}
    {selectedQuestion&&<div className="library-detail-overlay" onClick={()=>setSelectedQuestionId(null)}><aside className="library-detail-drawer" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><header><div><p className="section-kicker">每日一题详情</p><h2>第{selectedQuestion.number}题</h2><p>{qSubjectName(selectedQuestion.subjectId)} · {selectedQuestion.source}</p></div><button onClick={()=>setSelectedQuestionId(null)}>×</button></header><div className="library-detail-scroll"><section><strong>题干</strong><p>{selectedQuestion.stem}</p></section><section className="library-detail-segments">{selectedQuestion.options.map(option=><div key={option.key}><span>{option.key}</span><p>{option.text}</p></div>)}</section><section className="library-detail-answer"><strong>正确答案</strong><p>{selectedQuestion.answer??'无文字答案，自行评判'}</p></section>{selectedQuestion.analysis&&<section><strong>解析</strong><p>{selectedQuestion.analysis}</p></section>}{selectedQuestion.law&&<section><strong>法条依据</strong><p>{selectedQuestion.law}</p></section>}</div><footer><button onClick={()=>void archiveQuestion(selectedQuestion)}>{selectedQuestion.archivedAt?'恢复':'归档'}</button>{!selectedQuestion.archivedAt&&<><button onClick={()=>copyQuestion(selectedQuestion)}>复制</button><button className="primary" onClick={()=>editQuestion(selectedQuestion)}>编辑题目 →</button></>}</footer></aside></div>}
    {cardDraft&&<EditorShell title={cards.some(card=>card.id===cardDraft.id)?'编辑知识卡':'新增知识卡'} busy={busy} onClose={()=>setCardDraft(null)} onSave={saveCard}><div className="content-editor-grid"><label>科目<select value={cardDraft.subjectId} onChange={e=>{const sid=e.target.value;setCardDraft({...cardDraft,subjectId:sid,chapterId:chapters.find(ch=>ch.subjectId===sid)?.id??''})}}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>章节<div className="editor-inline"><select value={cardDraft.chapterId} onChange={e=>setCardDraft({...cardDraft,chapterId:e.target.value})}><option value="">请选择</option>{chapters.filter(ch=>ch.subjectId===cardDraft.subjectId).map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select><button type="button" onClick={()=>void addChapter(cardDraft.subjectId)}>＋</button></div></label><label>类型<select value={cardDraft.type} onChange={e=>setCardDraft({...cardDraft,type:e.target.value as CardType})}><option value="mnemonic">口诀默写</option><option value="recall">普通背诵</option><option value="judgment">判断题</option></select></label>{cardDraft.type==='judgment'&&<label>正确结论<select value={cardDraft.judgmentAnswer?'true':'false'} onChange={e=>setCardDraft({...cardDraft,judgmentAnswer:e.target.value==='true',resetProgress:true})}><option value="true">正确</option><option value="false">错误</option></select></label>}<label className="wide">标题<input value={cardDraft.prompt} onChange={e=>setCardDraft({...cardDraft,prompt:e.target.value})}/></label><label className="wide">完整答案 / 口诀<textarea value={cardDraft.answer} onChange={e=>setCardDraft({...cardDraft,answer:e.target.value,resetProgress:true})}/></label><label className="wide">口诀对应（每行：片段 =&gt; 知识点）<textarea value={cardDraft.segmentText} onChange={e=>setCardDraft({...cardDraft,segmentText:e.target.value})}/></label><label className="wide">详细解释<textarea value={cardDraft.explanation} onChange={e=>setCardDraft({...cardDraft,explanation:e.target.value})}/></label><label>法条依据<input value={cardDraft.statute??''} onChange={e=>setCardDraft({...cardDraft,statute:e.target.value})}/></label><label>来源<input value={cardDraft.source} onChange={e=>setCardDraft({...cardDraft,source:e.target.value})}/></label><label className="wide">标签（逗号分隔）<input value={cardDraft.tags.join('，')} onChange={e=>setCardDraft({...cardDraft,tags:e.target.value.split(/[，,]/).map(t=>t.trim()).filter(Boolean)})}/></label><label className="editor-check wide"><input type="checkbox" checked={Boolean(cardDraft.resetProgress)} onChange={e=>setCardDraft({...cardDraft,resetProgress:e.target.checked})}/>保存后将本卡掌握状态重置为“未学习”（历史记录保留）</label></div></EditorShell>}
    {questionDraft&&<EditorShell title={questions.some(q=>q.id===questionDraft.id)?'编辑每日一题':'新增每日一题'} busy={busy} onClose={()=>setQuestionDraft(null)} onSave={saveQuestion}><div className="content-editor-grid"><label>科目<select value={questionDraft.subjectId} onChange={e=>{const id=e.target.value;const maxNumber=Math.max(0,...activeQuestions.filter(q=>q.subjectId===id).map(q=>q.number));setQuestionDraft({...questionDraft,subjectId:id,chapterId:undefined,number:maxNumber+1})}}>{dqSubjectOptions.map(subject=><option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>章节（可选）<select value={questionDraft.chapterId??''} onChange={e=>setQuestionDraft({...questionDraft,chapterId:e.target.value||undefined})}><option value="">不指定章节</option>{chapters.filter(ch=>ch.subjectId===canonicalSubject(questionDraft.subjectId)).map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select></label><label>题型<select value={questionDraft.qtype??'single'} onChange={e=>setQuestionDraft({...questionDraft,qtype:e.target.value as DQType})}><option value="single">单选</option><option value="multiple">多选</option><option value="uncertain">不定项</option></select></label><label>题号<input type="number" min="1" value={questionDraft.number} onChange={e=>setQuestionDraft({...questionDraft,number:Number(e.target.value)||1})}/></label><label className="wide">题干<textarea value={questionDraft.stem} onChange={e=>setQuestionDraft({...questionDraft,stem:e.target.value,resetProgress:true})}/></label><label className="wide">选项（每行如 A. 内容）<textarea value={questionDraft.optionText} onChange={e=>setQuestionDraft({...questionDraft,optionText:e.target.value,resetProgress:true})}/></label><label>正确答案<input value={questionDraft.answer??''} onChange={e=>setQuestionDraft({...questionDraft,answer:e.target.value,resetProgress:true})} placeholder="如 A 或 ACD；留空则自评"/></label><label>来源<input value={questionDraft.source} onChange={e=>setQuestionDraft({...questionDraft,source:e.target.value})}/></label><label className="wide">解析<textarea value={questionDraft.analysis??''} onChange={e=>setQuestionDraft({...questionDraft,analysis:e.target.value})}/></label><label>法条依据<input value={questionDraft.law??''} onChange={e=>setQuestionDraft({...questionDraft,law:e.target.value})}/></label><label>标签<input value={questionDraft.tags?.join('，')??''} onChange={e=>setQuestionDraft({...questionDraft,tags:e.target.value.split(/[，,]/).map(t=>t.trim()).filter(Boolean)})}/></label><label className="editor-check wide"><input type="checkbox" checked={Boolean(questionDraft.resetProgress)} onChange={e=>setQuestionDraft({...questionDraft,resetProgress:e.target.checked})}/>保存后重置本题作答状态（历史作答日志保留）</label></div></EditorShell>}
  </section>;
}

function EditorShell({title,busy,onClose,onSave,children}:{title:string;busy:boolean;onClose():void;onSave():Promise<void>;children:ReactNode}) {
  return <div className="content-editor-overlay" onClick={onClose}><section className="content-editor" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><header><div><p className="section-kicker">当前账号独立内容</p><h2>{title}</h2></div><button type="button" onClick={onClose}>×</button></header><div className="content-editor-body">{children}</div><footer><button type="button" onClick={onClose}>取消</button><button className="primary" type="button" disabled={busy} onClick={()=>void onSave()}>{busy?'正在保存…':'保存内容 →'}</button></footer></section></div>;
}
